// Code generated by entc, DO NOT EDIT.

package roleukm

import (
	"github.com/confus1on/UKM/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// StatusRole applies equality check predicate on the "status_role" field. It's identical to StatusRoleEQ.
func StatusRole(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatusRole), v))
	})
}

// StatusRoleEQ applies the EQ predicate on the "status_role" field.
func StatusRoleEQ(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatusRole), v))
	})
}

// StatusRoleNEQ applies the NEQ predicate on the "status_role" field.
func StatusRoleNEQ(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatusRole), v))
	})
}

// StatusRoleIn applies the In predicate on the "status_role" field.
func StatusRoleIn(vs ...string) predicate.RoleUKM {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoleUKM(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatusRole), v...))
	})
}

// StatusRoleNotIn applies the NotIn predicate on the "status_role" field.
func StatusRoleNotIn(vs ...string) predicate.RoleUKM {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoleUKM(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatusRole), v...))
	})
}

// StatusRoleGT applies the GT predicate on the "status_role" field.
func StatusRoleGT(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatusRole), v))
	})
}

// StatusRoleGTE applies the GTE predicate on the "status_role" field.
func StatusRoleGTE(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatusRole), v))
	})
}

// StatusRoleLT applies the LT predicate on the "status_role" field.
func StatusRoleLT(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatusRole), v))
	})
}

// StatusRoleLTE applies the LTE predicate on the "status_role" field.
func StatusRoleLTE(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatusRole), v))
	})
}

// StatusRoleContains applies the Contains predicate on the "status_role" field.
func StatusRoleContains(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStatusRole), v))
	})
}

// StatusRoleHasPrefix applies the HasPrefix predicate on the "status_role" field.
func StatusRoleHasPrefix(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStatusRole), v))
	})
}

// StatusRoleHasSuffix applies the HasSuffix predicate on the "status_role" field.
func StatusRoleHasSuffix(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStatusRole), v))
	})
}

// StatusRoleEqualFold applies the EqualFold predicate on the "status_role" field.
func StatusRoleEqualFold(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStatusRole), v))
	})
}

// StatusRoleContainsFold applies the ContainsFold predicate on the "status_role" field.
func StatusRoleContainsFold(v string) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStatusRole), v))
	})
}

// HasProfileRoles applies the HasEdge predicate on the "profile_roles" edge.
func HasProfileRoles() predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProfileRolesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProfileRolesTable, ProfileRolesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfileRolesWith applies the HasEdge predicate on the "profile_roles" edge with a given conditions (other predicates).
func HasProfileRolesWith(preds ...predicate.ProfileUKM) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProfileRolesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProfileRolesTable, ProfileRolesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.RoleUKM) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.RoleUKM) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoleUKM) predicate.RoleUKM {
	return predicate.RoleUKM(func(s *sql.Selector) {
		p(s.Not())
	})
}
