// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/confus1on/UKM/ent/runtime.go

const (
	Version = "v0.1.4"                                          // Version of ent codegen.
	Sum     = "h1:1Y9icmCryGStA4e8hfNV0VS4wQkoIVZI3tzisus1jTM=" // Sum of ent codegen.
)
