// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"time"

	"github.com/confus1on/UKM/ent/profile"
	"github.com/confus1on/UKM/ent/role"
	"github.com/confus1on/UKM/ent/ukm"
	"github.com/confus1on/UKM/ent/user"

	"github.com/facebookincubator/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeProfile = "Profile"
	TypeRole    = "Role"
	TypeUkm     = "Ukm"
	TypeUser    = "User"
)

// ProfileMutation represents an operation that mutate the Profiles
// nodes in the graph.
type ProfileMutation struct {
	config
	op              Op
	typ             string
	id              *int
	firstName       *string
	lastName        *string
	jk              *profile.Jk
	address         *string
	birth_date      *string
	year_generation *string
	phone           *string
	status          *bool
	img_profile     *string
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	owner           map[int]struct{}
	removedowner    map[int]struct{}
	ukm             map[int]struct{}
	removedukm      map[int]struct{}
}

var _ ent.Mutation = (*ProfileMutation)(nil)

// newProfileMutation creates new mutation for $n.Name.
func newProfileMutation(c config, op Op) *ProfileMutation {
	return &ProfileMutation{
		config:        c,
		op:            op,
		typ:           TypeProfile,
		clearedFields: make(map[string]struct{}),
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProfileMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProfileMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *ProfileMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetFirstName sets the firstName field.
func (m *ProfileMutation) SetFirstName(s string) {
	m.firstName = &s
}

// FirstName returns the firstName value in the mutation.
func (m *ProfileMutation) FirstName() (r string, exists bool) {
	v := m.firstName
	if v == nil {
		return
	}
	return *v, true
}

// ResetFirstName reset all changes of the firstName field.
func (m *ProfileMutation) ResetFirstName() {
	m.firstName = nil
}

// SetLastName sets the lastName field.
func (m *ProfileMutation) SetLastName(s string) {
	m.lastName = &s
}

// LastName returns the lastName value in the mutation.
func (m *ProfileMutation) LastName() (r string, exists bool) {
	v := m.lastName
	if v == nil {
		return
	}
	return *v, true
}

// ResetLastName reset all changes of the lastName field.
func (m *ProfileMutation) ResetLastName() {
	m.lastName = nil
}

// SetJk sets the jk field.
func (m *ProfileMutation) SetJk(pr profile.Jk) {
	m.jk = &pr
}

// Jk returns the jk value in the mutation.
func (m *ProfileMutation) Jk() (r profile.Jk, exists bool) {
	v := m.jk
	if v == nil {
		return
	}
	return *v, true
}

// ResetJk reset all changes of the jk field.
func (m *ProfileMutation) ResetJk() {
	m.jk = nil
}

// SetAddress sets the address field.
func (m *ProfileMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the address value in the mutation.
func (m *ProfileMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// ClearAddress clears the value of address.
func (m *ProfileMutation) ClearAddress() {
	m.address = nil
	m.clearedFields[profile.FieldAddress] = struct{}{}
}

// AddressCleared returns if the field address was cleared in this mutation.
func (m *ProfileMutation) AddressCleared() bool {
	_, ok := m.clearedFields[profile.FieldAddress]
	return ok
}

// ResetAddress reset all changes of the address field.
func (m *ProfileMutation) ResetAddress() {
	m.address = nil
	delete(m.clearedFields, profile.FieldAddress)
}

// SetBirthDate sets the birth_date field.
func (m *ProfileMutation) SetBirthDate(s string) {
	m.birth_date = &s
}

// BirthDate returns the birth_date value in the mutation.
func (m *ProfileMutation) BirthDate() (r string, exists bool) {
	v := m.birth_date
	if v == nil {
		return
	}
	return *v, true
}

// ClearBirthDate clears the value of birth_date.
func (m *ProfileMutation) ClearBirthDate() {
	m.birth_date = nil
	m.clearedFields[profile.FieldBirthDate] = struct{}{}
}

// BirthDateCleared returns if the field birth_date was cleared in this mutation.
func (m *ProfileMutation) BirthDateCleared() bool {
	_, ok := m.clearedFields[profile.FieldBirthDate]
	return ok
}

// ResetBirthDate reset all changes of the birth_date field.
func (m *ProfileMutation) ResetBirthDate() {
	m.birth_date = nil
	delete(m.clearedFields, profile.FieldBirthDate)
}

// SetYearGeneration sets the year_generation field.
func (m *ProfileMutation) SetYearGeneration(s string) {
	m.year_generation = &s
}

// YearGeneration returns the year_generation value in the mutation.
func (m *ProfileMutation) YearGeneration() (r string, exists bool) {
	v := m.year_generation
	if v == nil {
		return
	}
	return *v, true
}

// ResetYearGeneration reset all changes of the year_generation field.
func (m *ProfileMutation) ResetYearGeneration() {
	m.year_generation = nil
}

// SetPhone sets the phone field.
func (m *ProfileMutation) SetPhone(s string) {
	m.phone = &s
}

// Phone returns the phone value in the mutation.
func (m *ProfileMutation) Phone() (r string, exists bool) {
	v := m.phone
	if v == nil {
		return
	}
	return *v, true
}

// ResetPhone reset all changes of the phone field.
func (m *ProfileMutation) ResetPhone() {
	m.phone = nil
}

// SetStatus sets the status field.
func (m *ProfileMutation) SetStatus(b bool) {
	m.status = &b
}

// Status returns the status value in the mutation.
func (m *ProfileMutation) Status() (r bool, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus reset all changes of the status field.
func (m *ProfileMutation) ResetStatus() {
	m.status = nil
}

// SetImgProfile sets the img_profile field.
func (m *ProfileMutation) SetImgProfile(s string) {
	m.img_profile = &s
}

// ImgProfile returns the img_profile value in the mutation.
func (m *ProfileMutation) ImgProfile() (r string, exists bool) {
	v := m.img_profile
	if v == nil {
		return
	}
	return *v, true
}

// ResetImgProfile reset all changes of the img_profile field.
func (m *ProfileMutation) ResetImgProfile() {
	m.img_profile = nil
}

// SetCreatedAt sets the created_at field.
func (m *ProfileMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the created_at value in the mutation.
func (m *ProfileMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt reset all changes of the created_at field.
func (m *ProfileMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the updated_at field.
func (m *ProfileMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the updated_at value in the mutation.
func (m *ProfileMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedAt reset all changes of the updated_at field.
func (m *ProfileMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddOwnerIDs adds the owner edge to User by ids.
func (m *ProfileMutation) AddOwnerIDs(ids ...int) {
	if m.owner == nil {
		m.owner = make(map[int]struct{})
	}
	for i := range ids {
		m.owner[ids[i]] = struct{}{}
	}
}

// RemoveOwnerIDs removes the owner edge to User by ids.
func (m *ProfileMutation) RemoveOwnerIDs(ids ...int) {
	if m.removedowner == nil {
		m.removedowner = make(map[int]struct{})
	}
	for i := range ids {
		m.removedowner[ids[i]] = struct{}{}
	}
}

// RemovedOwner returns the removed ids of owner.
func (m *ProfileMutation) RemovedOwnerIDs() (ids []int) {
	for id := range m.removedowner {
		ids = append(ids, id)
	}
	return
}

// OwnerIDs returns the owner ids in the mutation.
func (m *ProfileMutation) OwnerIDs() (ids []int) {
	for id := range m.owner {
		ids = append(ids, id)
	}
	return
}

// ResetOwner reset all changes of the owner edge.
func (m *ProfileMutation) ResetOwner() {
	m.owner = nil
	m.removedowner = nil
}

// AddUkmIDs adds the ukm edge to Ukm by ids.
func (m *ProfileMutation) AddUkmIDs(ids ...int) {
	if m.ukm == nil {
		m.ukm = make(map[int]struct{})
	}
	for i := range ids {
		m.ukm[ids[i]] = struct{}{}
	}
}

// RemoveUkmIDs removes the ukm edge to Ukm by ids.
func (m *ProfileMutation) RemoveUkmIDs(ids ...int) {
	if m.removedukm == nil {
		m.removedukm = make(map[int]struct{})
	}
	for i := range ids {
		m.removedukm[ids[i]] = struct{}{}
	}
}

// RemovedUkm returns the removed ids of ukm.
func (m *ProfileMutation) RemovedUkmIDs() (ids []int) {
	for id := range m.removedukm {
		ids = append(ids, id)
	}
	return
}

// UkmIDs returns the ukm ids in the mutation.
func (m *ProfileMutation) UkmIDs() (ids []int) {
	for id := range m.ukm {
		ids = append(ids, id)
	}
	return
}

// ResetUkm reset all changes of the ukm edge.
func (m *ProfileMutation) ResetUkm() {
	m.ukm = nil
	m.removedukm = nil
}

// Op returns the operation name.
func (m *ProfileMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Profile).
func (m *ProfileMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *ProfileMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.firstName != nil {
		fields = append(fields, profile.FieldFirstName)
	}
	if m.lastName != nil {
		fields = append(fields, profile.FieldLastName)
	}
	if m.jk != nil {
		fields = append(fields, profile.FieldJk)
	}
	if m.address != nil {
		fields = append(fields, profile.FieldAddress)
	}
	if m.birth_date != nil {
		fields = append(fields, profile.FieldBirthDate)
	}
	if m.year_generation != nil {
		fields = append(fields, profile.FieldYearGeneration)
	}
	if m.phone != nil {
		fields = append(fields, profile.FieldPhone)
	}
	if m.status != nil {
		fields = append(fields, profile.FieldStatus)
	}
	if m.img_profile != nil {
		fields = append(fields, profile.FieldImgProfile)
	}
	if m.created_at != nil {
		fields = append(fields, profile.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, profile.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *ProfileMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case profile.FieldFirstName:
		return m.FirstName()
	case profile.FieldLastName:
		return m.LastName()
	case profile.FieldJk:
		return m.Jk()
	case profile.FieldAddress:
		return m.Address()
	case profile.FieldBirthDate:
		return m.BirthDate()
	case profile.FieldYearGeneration:
		return m.YearGeneration()
	case profile.FieldPhone:
		return m.Phone()
	case profile.FieldStatus:
		return m.Status()
	case profile.FieldImgProfile:
		return m.ImgProfile()
	case profile.FieldCreatedAt:
		return m.CreatedAt()
	case profile.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *ProfileMutation) SetField(name string, value ent.Value) error {
	switch name {
	case profile.FieldFirstName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFirstName(v)
		return nil
	case profile.FieldLastName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastName(v)
		return nil
	case profile.FieldJk:
		v, ok := value.(profile.Jk)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJk(v)
		return nil
	case profile.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case profile.FieldBirthDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBirthDate(v)
		return nil
	case profile.FieldYearGeneration:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetYearGeneration(v)
		return nil
	case profile.FieldPhone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhone(v)
		return nil
	case profile.FieldStatus:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case profile.FieldImgProfile:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImgProfile(v)
		return nil
	case profile.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case profile.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Profile field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *ProfileMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *ProfileMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *ProfileMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Profile numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *ProfileMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(profile.FieldAddress) {
		fields = append(fields, profile.FieldAddress)
	}
	if m.FieldCleared(profile.FieldBirthDate) {
		fields = append(fields, profile.FieldBirthDate)
	}
	return fields
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *ProfileMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProfileMutation) ClearField(name string) error {
	switch name {
	case profile.FieldAddress:
		m.ClearAddress()
		return nil
	case profile.FieldBirthDate:
		m.ClearBirthDate()
		return nil
	}
	return fmt.Errorf("unknown Profile nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *ProfileMutation) ResetField(name string) error {
	switch name {
	case profile.FieldFirstName:
		m.ResetFirstName()
		return nil
	case profile.FieldLastName:
		m.ResetLastName()
		return nil
	case profile.FieldJk:
		m.ResetJk()
		return nil
	case profile.FieldAddress:
		m.ResetAddress()
		return nil
	case profile.FieldBirthDate:
		m.ResetBirthDate()
		return nil
	case profile.FieldYearGeneration:
		m.ResetYearGeneration()
		return nil
	case profile.FieldPhone:
		m.ResetPhone()
		return nil
	case profile.FieldStatus:
		m.ResetStatus()
		return nil
	case profile.FieldImgProfile:
		m.ResetImgProfile()
		return nil
	case profile.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case profile.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Profile field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *ProfileMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, profile.EdgeOwner)
	}
	if m.ukm != nil {
		edges = append(edges, profile.EdgeUkm)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *ProfileMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case profile.EdgeOwner:
		ids := make([]ent.Value, 0, len(m.owner))
		for id := range m.owner {
			ids = append(ids, id)
		}
		return ids
	case profile.EdgeUkm:
		ids := make([]ent.Value, 0, len(m.ukm))
		for id := range m.ukm {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *ProfileMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedowner != nil {
		edges = append(edges, profile.EdgeOwner)
	}
	if m.removedukm != nil {
		edges = append(edges, profile.EdgeUkm)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *ProfileMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case profile.EdgeOwner:
		ids := make([]ent.Value, 0, len(m.removedowner))
		for id := range m.removedowner {
			ids = append(ids, id)
		}
		return ids
	case profile.EdgeUkm:
		ids := make([]ent.Value, 0, len(m.removedukm))
		for id := range m.removedukm {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *ProfileMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *ProfileMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *ProfileMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Profile unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *ProfileMutation) ResetEdge(name string) error {
	switch name {
	case profile.EdgeOwner:
		m.ResetOwner()
		return nil
	case profile.EdgeUkm:
		m.ResetUkm()
		return nil
	}
	return fmt.Errorf("unknown Profile edge %s", name)
}

// RoleMutation represents an operation that mutate the Roles
// nodes in the graph.
type RoleMutation struct {
	config
	op            Op
	typ           string
	id            *int
	value         *string
	clearedFields map[string]struct{}
	access        map[int]struct{}
	removedaccess map[int]struct{}
}

var _ ent.Mutation = (*RoleMutation)(nil)

// newRoleMutation creates new mutation for $n.Name.
func newRoleMutation(c config, op Op) *RoleMutation {
	return &RoleMutation{
		config:        c,
		op:            op,
		typ:           TypeRole,
		clearedFields: make(map[string]struct{}),
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RoleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RoleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *RoleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetValue sets the value field.
func (m *RoleMutation) SetValue(s string) {
	m.value = &s
}

// Value returns the value value in the mutation.
func (m *RoleMutation) Value() (r string, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue reset all changes of the value field.
func (m *RoleMutation) ResetValue() {
	m.value = nil
}

// AddAccesIDs adds the access edge to User by ids.
func (m *RoleMutation) AddAccesIDs(ids ...int) {
	if m.access == nil {
		m.access = make(map[int]struct{})
	}
	for i := range ids {
		m.access[ids[i]] = struct{}{}
	}
}

// RemoveAccesIDs removes the access edge to User by ids.
func (m *RoleMutation) RemoveAccesIDs(ids ...int) {
	if m.removedaccess == nil {
		m.removedaccess = make(map[int]struct{})
	}
	for i := range ids {
		m.removedaccess[ids[i]] = struct{}{}
	}
}

// RemovedAccess returns the removed ids of access.
func (m *RoleMutation) RemovedAccessIDs() (ids []int) {
	for id := range m.removedaccess {
		ids = append(ids, id)
	}
	return
}

// AccessIDs returns the access ids in the mutation.
func (m *RoleMutation) AccessIDs() (ids []int) {
	for id := range m.access {
		ids = append(ids, id)
	}
	return
}

// ResetAccess reset all changes of the access edge.
func (m *RoleMutation) ResetAccess() {
	m.access = nil
	m.removedaccess = nil
}

// Op returns the operation name.
func (m *RoleMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Role).
func (m *RoleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *RoleMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.value != nil {
		fields = append(fields, role.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *RoleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case role.FieldValue:
		return m.Value()
	}
	return nil, false
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *RoleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case role.FieldValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Role field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *RoleMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *RoleMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *RoleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Role numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *RoleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *RoleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *RoleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Role nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *RoleMutation) ResetField(name string) error {
	switch name {
	case role.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Role field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *RoleMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.access != nil {
		edges = append(edges, role.EdgeAccess)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *RoleMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case role.EdgeAccess:
		ids := make([]ent.Value, 0, len(m.access))
		for id := range m.access {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *RoleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedaccess != nil {
		edges = append(edges, role.EdgeAccess)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *RoleMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case role.EdgeAccess:
		ids := make([]ent.Value, 0, len(m.removedaccess))
		for id := range m.removedaccess {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *RoleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *RoleMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *RoleMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Role unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *RoleMutation) ResetEdge(name string) error {
	switch name {
	case role.EdgeAccess:
		m.ResetAccess()
		return nil
	}
	return fmt.Errorf("unknown Role edge %s", name)
}

// UkmMutation represents an operation that mutate the Ukms
// nodes in the graph.
type UkmMutation struct {
	config
	op              Op
	typ             string
	id              *int
	name            *string
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	profiles        map[int]struct{}
	removedprofiles map[int]struct{}
}

var _ ent.Mutation = (*UkmMutation)(nil)

// newUkmMutation creates new mutation for $n.Name.
func newUkmMutation(c config, op Op) *UkmMutation {
	return &UkmMutation{
		config:        c,
		op:            op,
		typ:           TypeUkm,
		clearedFields: make(map[string]struct{}),
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UkmMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UkmMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *UkmMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the name field.
func (m *UkmMutation) SetName(s string) {
	m.name = &s
}

// Name returns the name value in the mutation.
func (m *UkmMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// ResetName reset all changes of the name field.
func (m *UkmMutation) ResetName() {
	m.name = nil
}

// SetCreatedAt sets the created_at field.
func (m *UkmMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the created_at value in the mutation.
func (m *UkmMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt reset all changes of the created_at field.
func (m *UkmMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the updated_at field.
func (m *UkmMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the updated_at value in the mutation.
func (m *UkmMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedAt reset all changes of the updated_at field.
func (m *UkmMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddProfileIDs adds the profiles edge to Profile by ids.
func (m *UkmMutation) AddProfileIDs(ids ...int) {
	if m.profiles == nil {
		m.profiles = make(map[int]struct{})
	}
	for i := range ids {
		m.profiles[ids[i]] = struct{}{}
	}
}

// RemoveProfileIDs removes the profiles edge to Profile by ids.
func (m *UkmMutation) RemoveProfileIDs(ids ...int) {
	if m.removedprofiles == nil {
		m.removedprofiles = make(map[int]struct{})
	}
	for i := range ids {
		m.removedprofiles[ids[i]] = struct{}{}
	}
}

// RemovedProfiles returns the removed ids of profiles.
func (m *UkmMutation) RemovedProfilesIDs() (ids []int) {
	for id := range m.removedprofiles {
		ids = append(ids, id)
	}
	return
}

// ProfilesIDs returns the profiles ids in the mutation.
func (m *UkmMutation) ProfilesIDs() (ids []int) {
	for id := range m.profiles {
		ids = append(ids, id)
	}
	return
}

// ResetProfiles reset all changes of the profiles edge.
func (m *UkmMutation) ResetProfiles() {
	m.profiles = nil
	m.removedprofiles = nil
}

// Op returns the operation name.
func (m *UkmMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Ukm).
func (m *UkmMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *UkmMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, ukm.FieldName)
	}
	if m.created_at != nil {
		fields = append(fields, ukm.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, ukm.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *UkmMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ukm.FieldName:
		return m.Name()
	case ukm.FieldCreatedAt:
		return m.CreatedAt()
	case ukm.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UkmMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ukm.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case ukm.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case ukm.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Ukm field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *UkmMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *UkmMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UkmMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Ukm numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *UkmMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *UkmMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *UkmMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Ukm nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *UkmMutation) ResetField(name string) error {
	switch name {
	case ukm.FieldName:
		m.ResetName()
		return nil
	case ukm.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case ukm.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Ukm field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *UkmMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.profiles != nil {
		edges = append(edges, ukm.EdgeProfiles)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *UkmMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ukm.EdgeProfiles:
		ids := make([]ent.Value, 0, len(m.profiles))
		for id := range m.profiles {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *UkmMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedprofiles != nil {
		edges = append(edges, ukm.EdgeProfiles)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *UkmMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case ukm.EdgeProfiles:
		ids := make([]ent.Value, 0, len(m.removedprofiles))
		for id := range m.removedprofiles {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *UkmMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *UkmMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *UkmMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Ukm unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *UkmMutation) ResetEdge(name string) error {
	switch name {
	case ukm.EdgeProfiles:
		m.ResetProfiles()
		return nil
	}
	return fmt.Errorf("unknown Ukm edge %s", name)
}

// UserMutation represents an operation that mutate the Users
// nodes in the graph.
type UserMutation struct {
	config
	op             Op
	typ            string
	id             *int
	email          *string
	password       *string
	created_at     *time.Time
	updated_at     *time.Time
	clearedFields  map[string]struct{}
	profile        *int
	clearedprofile bool
	role           *int
	clearedrole    bool
}

var _ ent.Mutation = (*UserMutation)(nil)

// newUserMutation creates new mutation for $n.Name.
func newUserMutation(c config, op Op) *UserMutation {
	return &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetEmail sets the email field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the email value in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// ResetEmail reset all changes of the email field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetPassword sets the password field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the password value in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// ResetPassword reset all changes of the password field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetCreatedAt sets the created_at field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the created_at value in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt reset all changes of the created_at field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the updated_at field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the updated_at value in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedAt reset all changes of the updated_at field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetProfileID sets the profile edge to Profile by id.
func (m *UserMutation) SetProfileID(id int) {
	m.profile = &id
}

// ClearProfile clears the profile edge to Profile.
func (m *UserMutation) ClearProfile() {
	m.clearedprofile = true
}

// ProfileCleared returns if the edge profile was cleared.
func (m *UserMutation) ProfileCleared() bool {
	return m.clearedprofile
}

// ProfileID returns the profile id in the mutation.
func (m *UserMutation) ProfileID() (id int, exists bool) {
	if m.profile != nil {
		return *m.profile, true
	}
	return
}

// ProfileIDs returns the profile ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// ProfileID instead. It exists only for internal usage by the builders.
func (m *UserMutation) ProfileIDs() (ids []int) {
	if id := m.profile; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProfile reset all changes of the profile edge.
func (m *UserMutation) ResetProfile() {
	m.profile = nil
	m.clearedprofile = false
}

// SetRoleID sets the role edge to Role by id.
func (m *UserMutation) SetRoleID(id int) {
	m.role = &id
}

// ClearRole clears the role edge to Role.
func (m *UserMutation) ClearRole() {
	m.clearedrole = true
}

// RoleCleared returns if the edge role was cleared.
func (m *UserMutation) RoleCleared() bool {
	return m.clearedrole
}

// RoleID returns the role id in the mutation.
func (m *UserMutation) RoleID() (id int, exists bool) {
	if m.role != nil {
		return *m.role, true
	}
	return
}

// RoleIDs returns the role ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// RoleID instead. It exists only for internal usage by the builders.
func (m *UserMutation) RoleIDs() (ids []int) {
	if id := m.role; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRole reset all changes of the role edge.
func (m *UserMutation) ResetRole() {
	m.role = nil
	m.clearedrole = false
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldEmail:
		return m.Email()
	case user.FieldPassword:
		return m.Password()
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.profile != nil {
		edges = append(edges, user.EdgeProfile)
	}
	if m.role != nil {
		edges = append(edges, user.EdgeRole)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeProfile:
		if id := m.profile; id != nil {
			return []ent.Value{*id}
		}
	case user.EdgeRole:
		if id := m.role; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedprofile {
		edges = append(edges, user.EdgeProfile)
	}
	if m.clearedrole {
		edges = append(edges, user.EdgeRole)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeProfile:
		return m.clearedprofile
	case user.EdgeRole:
		return m.clearedrole
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	case user.EdgeProfile:
		m.ClearProfile()
		return nil
	case user.EdgeRole:
		m.ClearRole()
		return nil
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeProfile:
		m.ResetProfile()
		return nil
	case user.EdgeRole:
		m.ResetRole()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
