// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/confus1on/UKM/ent/predicate"
	"github.com/confus1on/UKM/ent/profileukm"
	"github.com/confus1on/UKM/ent/roleukm"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoleUKMQuery is the builder for querying RoleUKM entities.
type RoleUKMQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.RoleUKM
	// eager-loading edges.
	withProfileRoles *ProfileUKMQuery
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (ruq *RoleUKMQuery) Where(ps ...predicate.RoleUKM) *RoleUKMQuery {
	ruq.predicates = append(ruq.predicates, ps...)
	return ruq
}

// Limit adds a limit step to the query.
func (ruq *RoleUKMQuery) Limit(limit int) *RoleUKMQuery {
	ruq.limit = &limit
	return ruq
}

// Offset adds an offset step to the query.
func (ruq *RoleUKMQuery) Offset(offset int) *RoleUKMQuery {
	ruq.offset = &offset
	return ruq
}

// Order adds an order step to the query.
func (ruq *RoleUKMQuery) Order(o ...Order) *RoleUKMQuery {
	ruq.order = append(ruq.order, o...)
	return ruq
}

// QueryProfileRoles chains the current query on the profile_roles edge.
func (ruq *RoleUKMQuery) QueryProfileRoles() *ProfileUKMQuery {
	query := &ProfileUKMQuery{config: ruq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(roleukm.Table, roleukm.FieldID, ruq.sqlQuery()),
		sqlgraph.To(profileukm.Table, profileukm.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, roleukm.ProfileRolesTable, roleukm.ProfileRolesColumn),
	)
	query.sql = sqlgraph.SetNeighbors(ruq.driver.Dialect(), step)
	return query
}

// First returns the first RoleUKM entity in the query. Returns *NotFoundError when no roleukm was found.
func (ruq *RoleUKMQuery) First(ctx context.Context) (*RoleUKM, error) {
	rus, err := ruq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(rus) == 0 {
		return nil, &NotFoundError{roleukm.Label}
	}
	return rus[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ruq *RoleUKMQuery) FirstX(ctx context.Context) *RoleUKM {
	ru, err := ruq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ru
}

// FirstID returns the first RoleUKM id in the query. Returns *NotFoundError when no id was found.
func (ruq *RoleUKMQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ruq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roleukm.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (ruq *RoleUKMQuery) FirstXID(ctx context.Context) int {
	id, err := ruq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only RoleUKM entity in the query, returns an error if not exactly one entity was returned.
func (ruq *RoleUKMQuery) Only(ctx context.Context) (*RoleUKM, error) {
	rus, err := ruq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(rus) {
	case 1:
		return rus[0], nil
	case 0:
		return nil, &NotFoundError{roleukm.Label}
	default:
		return nil, &NotSingularError{roleukm.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ruq *RoleUKMQuery) OnlyX(ctx context.Context) *RoleUKM {
	ru, err := ruq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ru
}

// OnlyID returns the only RoleUKM id in the query, returns an error if not exactly one id was returned.
func (ruq *RoleUKMQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ruq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roleukm.Label}
	default:
		err = &NotSingularError{roleukm.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (ruq *RoleUKMQuery) OnlyXID(ctx context.Context) int {
	id, err := ruq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoleUKMs.
func (ruq *RoleUKMQuery) All(ctx context.Context) ([]*RoleUKM, error) {
	return ruq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ruq *RoleUKMQuery) AllX(ctx context.Context) []*RoleUKM {
	rus, err := ruq.All(ctx)
	if err != nil {
		panic(err)
	}
	return rus
}

// IDs executes the query and returns a list of RoleUKM ids.
func (ruq *RoleUKMQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ruq.Select(roleukm.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ruq *RoleUKMQuery) IDsX(ctx context.Context) []int {
	ids, err := ruq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ruq *RoleUKMQuery) Count(ctx context.Context) (int, error) {
	return ruq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ruq *RoleUKMQuery) CountX(ctx context.Context) int {
	count, err := ruq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ruq *RoleUKMQuery) Exist(ctx context.Context) (bool, error) {
	return ruq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ruq *RoleUKMQuery) ExistX(ctx context.Context) bool {
	exist, err := ruq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ruq *RoleUKMQuery) Clone() *RoleUKMQuery {
	return &RoleUKMQuery{
		config:     ruq.config,
		limit:      ruq.limit,
		offset:     ruq.offset,
		order:      append([]Order{}, ruq.order...),
		unique:     append([]string{}, ruq.unique...),
		predicates: append([]predicate.RoleUKM{}, ruq.predicates...),
		// clone intermediate query.
		sql: ruq.sql.Clone(),
	}
}

//  WithProfileRoles tells the query-builder to eager-loads the nodes that are connected to
// the "profile_roles" edge. The optional arguments used to configure the query builder of the edge.
func (ruq *RoleUKMQuery) WithProfileRoles(opts ...func(*ProfileUKMQuery)) *RoleUKMQuery {
	query := &ProfileUKMQuery{config: ruq.config}
	for _, opt := range opts {
		opt(query)
	}
	ruq.withProfileRoles = query
	return ruq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StatusRole string `json:"status_role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoleUKM.Query().
//		GroupBy(roleukm.FieldStatusRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ruq *RoleUKMQuery) GroupBy(field string, fields ...string) *RoleUKMGroupBy {
	group := &RoleUKMGroupBy{config: ruq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = ruq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		StatusRole string `json:"status_role,omitempty"`
//	}
//
//	client.RoleUKM.Query().
//		Select(roleukm.FieldStatusRole).
//		Scan(ctx, &v)
//
func (ruq *RoleUKMQuery) Select(field string, fields ...string) *RoleUKMSelect {
	selector := &RoleUKMSelect{config: ruq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = ruq.sqlQuery()
	return selector
}

func (ruq *RoleUKMQuery) sqlAll(ctx context.Context) ([]*RoleUKM, error) {
	var (
		nodes       = []*RoleUKM{}
		_spec       = ruq.querySpec()
		loadedTypes = [1]bool{
			ruq.withProfileRoles != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &RoleUKM{config: ruq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, ruq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ruq.withProfileRoles; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*RoleUKM)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.ProfileUKM(func(s *sql.Selector) {
			s.Where(sql.InValues(roleukm.ProfileRolesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.role_ukm_profile_roles
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "role_ukm_profile_roles" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "role_ukm_profile_roles" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.ProfileRoles = append(node.Edges.ProfileRoles, n)
		}
	}

	return nodes, nil
}

func (ruq *RoleUKMQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ruq.querySpec()
	return sqlgraph.CountNodes(ctx, ruq.driver, _spec)
}

func (ruq *RoleUKMQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ruq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (ruq *RoleUKMQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roleukm.Table,
			Columns: roleukm.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roleukm.FieldID,
			},
		},
		From:   ruq.sql,
		Unique: true,
	}
	if ps := ruq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ruq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ruq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ruq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ruq *RoleUKMQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(ruq.driver.Dialect())
	t1 := builder.Table(roleukm.Table)
	selector := builder.Select(t1.Columns(roleukm.Columns...)...).From(t1)
	if ruq.sql != nil {
		selector = ruq.sql
		selector.Select(selector.Columns(roleukm.Columns...)...)
	}
	for _, p := range ruq.predicates {
		p(selector)
	}
	for _, p := range ruq.order {
		p(selector)
	}
	if offset := ruq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ruq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoleUKMGroupBy is the builder for group-by RoleUKM entities.
type RoleUKMGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rugb *RoleUKMGroupBy) Aggregate(fns ...Aggregate) *RoleUKMGroupBy {
	rugb.fns = append(rugb.fns, fns...)
	return rugb
}

// Scan applies the group-by query and scan the result into the given value.
func (rugb *RoleUKMGroupBy) Scan(ctx context.Context, v interface{}) error {
	return rugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rugb *RoleUKMGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (rugb *RoleUKMGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rugb.fields) > 1 {
		return nil, errors.New("ent: RoleUKMGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rugb *RoleUKMGroupBy) StringsX(ctx context.Context) []string {
	v, err := rugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (rugb *RoleUKMGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rugb.fields) > 1 {
		return nil, errors.New("ent: RoleUKMGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rugb *RoleUKMGroupBy) IntsX(ctx context.Context) []int {
	v, err := rugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (rugb *RoleUKMGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rugb.fields) > 1 {
		return nil, errors.New("ent: RoleUKMGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rugb *RoleUKMGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (rugb *RoleUKMGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rugb.fields) > 1 {
		return nil, errors.New("ent: RoleUKMGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rugb *RoleUKMGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rugb *RoleUKMGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rugb.sqlQuery().Query()
	if err := rugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rugb *RoleUKMGroupBy) sqlQuery() *sql.Selector {
	selector := rugb.sql
	columns := make([]string, 0, len(rugb.fields)+len(rugb.fns))
	columns = append(columns, rugb.fields...)
	for _, fn := range rugb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(rugb.fields...)
}

// RoleUKMSelect is the builder for select fields of RoleUKM entities.
type RoleUKMSelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (rus *RoleUKMSelect) Scan(ctx context.Context, v interface{}) error {
	return rus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rus *RoleUKMSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (rus *RoleUKMSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rus.fields) > 1 {
		return nil, errors.New("ent: RoleUKMSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rus *RoleUKMSelect) StringsX(ctx context.Context) []string {
	v, err := rus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (rus *RoleUKMSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rus.fields) > 1 {
		return nil, errors.New("ent: RoleUKMSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rus *RoleUKMSelect) IntsX(ctx context.Context) []int {
	v, err := rus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (rus *RoleUKMSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rus.fields) > 1 {
		return nil, errors.New("ent: RoleUKMSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rus *RoleUKMSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (rus *RoleUKMSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rus.fields) > 1 {
		return nil, errors.New("ent: RoleUKMSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rus *RoleUKMSelect) BoolsX(ctx context.Context) []bool {
	v, err := rus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rus *RoleUKMSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rus.sqlQuery().Query()
	if err := rus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rus *RoleUKMSelect) sqlQuery() sql.Querier {
	selector := rus.sql
	selector.Select(selector.Columns(rus.fields...)...)
	return selector
}
