// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "github.com/confus1on/UKM/internal/model"
	utils "github.com/confus1on/UKM/internal/utils"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUsecaseUKM is a mock of UsecaseUKM interface
type MockUsecaseUKM struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseUKMMockRecorder
}

// MockUsecaseUKMMockRecorder is the mock recorder for MockUsecaseUKM
type MockUsecaseUKMMockRecorder struct {
	mock *MockUsecaseUKM
}

// NewMockUsecaseUKM creates a new mock instance
func NewMockUsecaseUKM(ctrl *gomock.Controller) *MockUsecaseUKM {
	mock := &MockUsecaseUKM{ctrl: ctrl}
	mock.recorder = &MockUsecaseUKMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecaseUKM) EXPECT() *MockUsecaseUKMMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockUsecaseUKM) GetAll(ctx context.Context) (*model.ResponseGetAllUKM, *utils.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(*model.ResponseGetAllUKM)
	ret1, _ := ret[1].(*utils.Error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockUsecaseUKMMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUsecaseUKM)(nil).GetAll), ctx)
}

// RegisterUKM mocks base method
func (m *MockUsecaseUKM) RegisterUKM(ctx context.Context, profileID int, input model.InputRegisterUKM) (*model.ResponseRegisterUKM, *utils.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUKM", ctx, profileID, input)
	ret0, _ := ret[0].(*model.ResponseRegisterUKM)
	ret1, _ := ret[1].(*utils.Error)
	return ret0, ret1
}

// RegisterUKM indicates an expected call of RegisterUKM
func (mr *MockUsecaseUKMMockRecorder) RegisterUKM(ctx, profileID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUKM", reflect.TypeOf((*MockUsecaseUKM)(nil).RegisterUKM), ctx, profileID, input)
}

// UpdateUKM mocks base method
func (m *MockUsecaseUKM) UpdateUKM(ctx context.Context, id int, input model.InputUpdateUKM) (*model.ResponseUpdateUKM, *utils.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUKM", ctx, id, input)
	ret0, _ := ret[0].(*model.ResponseUpdateUKM)
	ret1, _ := ret[1].(*utils.Error)
	return ret0, ret1
}

// UpdateUKM indicates an expected call of UpdateUKM
func (mr *MockUsecaseUKMMockRecorder) UpdateUKM(ctx, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUKM", reflect.TypeOf((*MockUsecaseUKM)(nil).UpdateUKM), ctx, id, input)
}
