// Code generated by entc, DO NOT EDIT.

package role

const (
	// Label holds the string label denoting the role type in the database.
	Label = "role"
	// FieldID holds the string denoting the id field in the database.
	FieldID    = "id" // FieldValue holds the string denoting the value vertex property in the database.
	FieldValue = "value"

	// EdgeAccess holds the string denoting the access edge name in mutations.
	EdgeAccess = "access"

	// Table holds the table name of the role in the database.
	Table = "roles"
	// AccessTable is the table the holds the access relation/edge.
	AccessTable = "users"
	// AccessInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AccessInverseTable = "users"
	// AccessColumn is the table column denoting the access relation/edge.
	AccessColumn = "user_role"
)

// Columns holds all SQL columns for role fields.
var Columns = []string{
	FieldID,
	FieldValue,
}

var (
	// ValueValidator is a validator for the "value" field. It is called by the builders before save.
	ValueValidator func(string) error
)
