// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// ProfileUKM is the predicate function for profileukm builders.
type ProfileUKM func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleUKM is the predicate function for roleukm builders.
type RoleUKM func(*sql.Selector)

// Ukm is the predicate function for ukm builders.
type Ukm func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
