// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Ukm is the predicate function for ukm builders.
type Ukm func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
