// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	ent "github.com/confus1on/UKM/ent"
	model "github.com/confus1on/UKM/internal/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepositoryProfile is a mock of RepositoryProfile interface
type MockRepositoryProfile struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryProfileMockRecorder
}

// MockRepositoryProfileMockRecorder is the mock recorder for MockRepositoryProfile
type MockRepositoryProfileMockRecorder struct {
	mock *MockRepositoryProfile
}

// NewMockRepositoryProfile creates a new mock instance
func NewMockRepositoryProfile(ctrl *gomock.Controller) *MockRepositoryProfile {
	mock := &MockRepositoryProfile{ctrl: ctrl}
	mock.recorder = &MockRepositoryProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepositoryProfile) EXPECT() *MockRepositoryProfileMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method
func (m *MockRepositoryProfile) FindByEmail(ctx context.Context, email string) (*ent.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*ent.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail
func (mr *MockRepositoryProfileMockRecorder) FindByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockRepositoryProfile)(nil).FindByEmail), ctx, email)
}

// UpdateOne mocks base method
func (m *MockRepositoryProfile) UpdateOne(ctx context.Context, email string, input model.InputUpdateProfile) (*ent.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOne", ctx, email, input)
	ret0, _ := ret[0].(*ent.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOne indicates an expected call of UpdateOne
func (mr *MockRepositoryProfileMockRecorder) UpdateOne(ctx, email, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockRepositoryProfile)(nil).UpdateOne), ctx, email, input)
}
