version: "3.7"

services:
  ukm_api:
    image: ukm-organization:0.3.3
    ports:
      - 5000:5000
    depends_on:
      - ukm_db
    environment:
      DATABASE_URL: postgres://root:root@ukm_db:5432/ukmdevelopment?sslmode=disable
      DATABASE_NAME: ukmdevelopment

  ukm_db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local