name: Go workflow
on: [pull_request]
jobs:
  api-test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Go '1.14'
        uses: actions/setup-go@v1
        with:
            go-version: '1.14'
      - name: Run test
        run: cd api && go test -test.v -test.coverprofile=coverage.out -test.covermode=count ./...