name: API workflow
on: [pull_request]
jobs:
  api-test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Go '1.14'
        uses: actions/setup-go@v1
        with:
            go-version: '1.14'
      - name: Run test
        run: cd api && go test -test.v -test.coverprofile=coverage.out -test.covermode=count ./...
      - name: codecov check coverage
        env:
          CODECOV_TOKEN: "f803157f-4689-4383-8498-26ff8911c339"
        run: bash <(curl -s https://codecov.io/bash)

  api-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Go '1.14'
        uses: actions/setup-go@v1
        with:
            version: '1.14'
      - name: Setup golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7
          echo ::add-path::$HOME/bin
          echo ::add-path::$(go env GOPATH)/bin # for Go projects
      - run: cd api && golangci-lint run

  deploy-heroku:
    name: deploy-heroku
    runs-on: ubuntu-latest
    needs: api-test
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      HEROKU_APP_NAME: "ukm-backend"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Push to heroku
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master