name: Coverage workflow
on: 
  push:
    branches:
      - master
jobs:
  code-coverage:
    name: check-code-coverage
    runs-on: ubuntu-latest
    needs: [api-test]
    if: github.event.pull_request.merged
    steps:
      - name: codecov check coverage
        env:
          CODECOV_TOKEN: "f803157f-4689-4383-8498-26ff8911c339"
        run: bash <(curl -s https://codecov.io/bash)